export const RAINBOW_PROJECT_ID = import.meta.env.VITE_RAINBOW_PROJECT_ID;

export const TOKEN_FACTORY_CONTRACT_ADDRESS_LOCALHOST = import.meta.env
  .VITE_TOKEN_FACTORY_CONTRACT_ADDRESS_LOCALHOST;

export const TOKEN_FACTORY_CONTRACT_ADDRESS_SEPOLIA = import.meta.env
  .VITE_TOKEN_FACTORY_CONTRACT_ADDRESS_SEPOLIA;
